import Footer from "@/components/Footer";
// import Header from "@/components/Header";
import dynamic from "next/dynamic";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const Header = dynamic(() => import('../../components/Header'), { ssr: false })

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
